CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    name VARCHAR(255),
    phone VARCHAR(255),
    event_created TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    total_events_created INTEGER NOT NULL DEFAULT 0,
    event_joined TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    total_events_joined INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    location VARCHAR(255),
    date TIMESTAMP(6) WITHOUT TIME ZONE,
    event_type VARCHAR(255),
    max_participants INTEGER,
    total_participants INTEGER NOT NULL DEFAULT 0,
    owner_id BIGINT,
    participants TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    CONSTRAINT fk_events_owner
        FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_events_owner_id ON events (owner_id);

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_items_event
        FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_items_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_items_event_id ON items (event_id);
CREATE INDEX idx_items_user_id ON items (user_id);
